name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          link-to-sdk: true
      - name: Make gradlew executable and build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug -Pevvdroid.abis=arm64-v8a
      - uses: actions/upload-artifact@v4
        with:
          name: evvdroid-latest
          path: app/build/outputs/apk/debug/*.apk
